version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "toy-databse"
    ports:
      - "5432:5432"
    environment: #environment variables when database start up
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres  #postgresql has default name postgres
      - POSTGRES_PASSWORD=QQgood
    networks:
      - fullstack
    volumes: 
      - database_postgres:/var/lib/postgresql/data

  test:
    build: .
    container_name: "toy-api"
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD:  "QQgood"      
      DB_DB: "postgres"
      DB_HOST: "db"    # should match db as db service
      DB_TABLE:  "postgres"   #this should match "postgres", other wise the table can not be created
      DB_PORT: "5432"
      SSL_MODE: "disable"
    ports:
      - "8080:8080"  
    depends_on:
      - db    
    networks:
      - fullstack
volumes:
  database_postgres:

networks:
  fullstack:
      driver: bridge   